/**
 * Style Dictionary Build Pipeline
 *
 * Transforms W3C DTCG tokens into CSS custom properties
 * wrapped in a Tailwind v4 @theme block.
 *
 * Usage: node design-tokens/build.mjs
 */

import StyleDictionary from 'style-dictionary';

// Custom format: outputs CSS variables inside @theme { } for Tailwind v4
StyleDictionary.registerFormat({
  name: 'css/tailwind-theme',
  format({ dictionary, options }) {
    const header = options?.showFileHeader !== false
      ? '/* Generated by Style Dictionary — DO NOT EDIT */\n\n'
      : '';

    const variables = dictionary.allTokens
      .map((token) => {
        const comment = token.$description ? ` /* ${token.$description} */` : '';
        return `  --${token.name}: ${token.$value ?? token.value};${comment}`;
      })
      .join('\n');

    return `${header}@theme {\n${variables}\n}\n`;
  },
});

// Custom format: dark mode overrides in @media block using :root
StyleDictionary.registerFormat({
  name: 'css/dark-overrides',
  format({ dictionary, options }) {
    const header = options?.showFileHeader !== false
      ? '/* Generated by Style Dictionary — DO NOT EDIT */\n\n'
      : '';

    const variables = dictionary.allTokens
      .map((token) => `  --${token.name}: ${token.$value ?? token.value};`)
      .join('\n');

    return `${header}@media (prefers-color-scheme: dark) {\n  :root {\n${variables}\n  }\n}\n`;
  },
});

const sd = new StyleDictionary({
  log: { verbosity: 'default', warnings: 'disabled' },
  source: [
    'design-tokens/primitive/**/*.tokens.json',
    'design-tokens/semantic/**/*.tokens.json',
  ],
  usesDtcg: true,
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'src/styles/',
      files: [
        {
          destination: 'tokens.generated.css',
          format: 'css/tailwind-theme',
          options: {
            outputReferences: true,
            showFileHeader: true,
          },
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log('✓ Tokens built → src/styles/tokens.generated.css');
